### ISSUE TITLE
web版能看到书籍，到kindle页面看不到书，已经分组了

### ISSUE THREAD

**Issue by wevcat** [Suto-Commune/Kindle-Reader-Web-CLI#22]
错误如题  docker部署的
web版能看到书籍，到kindle页面看不到书
访问1000端口，会出现拒绝访问
访问5000端口正常，但是书架没书。。。
F12调试看到
 /index/main/log  404错误
`stderr: [Jan/11/2024-04:40:29][main.py(19)][INFO] Cannot Find the config.py,create the default config file.
stderr: [Jan/11/2024-04:40:30][func.py(38)][WARNING] CLONE_MODE Disable.
stderr: [Jan/11/2024-04:40:30][thread.py(54)][INFO] Doesn't OPEN AUTO_BACKUP.
stderr: 192.168.100.5 - - [2024-01-11 04:40:55] "GET / HTTP/1.1" 200 18238 1.071270
stderr: 192.168.100.5 - - [2024-01-11 04:40:55] "GET /assets/css/layout.css HTTP/1.1" 304 181 0.003808
stderr: 192.168.100.5 - - [2024-01-11 04:40:55] "GET /assets/js/myJQuery.js HTTP/1.1" 304 180 0.002464
stderr: 192.168.100.5 - - [2024-01-11 04:40:55] "GET /assets/js/title.js HTTP/1.1" 304 176 0.002230
stderr: 192.168.100.5 - - [2024-01-11 04:40:55] "GET /assets/js/hpage.js HTTP/1.1" 304 177 0.002117
stderr: 192.168.100.5 - - [2024-01-11 04:40:55] "GET /assets/js/booklist.js HTTP/1.1" 304 180 0.002079
stderr: 192.168.100.5 - - [2024-01-11 04:40:55] "GET /assets/js/layout.js HTTP/1.1" 304 178 0.002496
stderr: 192.168.100.5 - - [2024-01-11 04:40:55] "GET /assets/js/book.js HTTP/1.1" 304 175 0.002024
stderr: 192.168.100.5 - - [2024-01-11 04:40:55] "GET /assets/js/base16.js HTTP/1.1" 304 179 0.001871
stderr: 192.168.100.5 - - [2024-01-11 04:40:55] "GET /i/js/layout.js?t=1704948055228 HTTP/1.1" 404 331 0.001650
stderr: 192.168.100.5 - - [2024-01-11 04:40:55] "GET /i/js/booklist.js?t=1704948055280 HTTP/1.1" 404 331 0.001444
stderr: 192.168.100.5 - - [2024-01-11 04:40:55] "GET /index/main/log HTTP/1.1" 404 331 0.001630
stderr: com.jayway.jsonpath.PathNotFoundException: No results for path: $['category']
stderr: 	at com.jayway.jsonpath.internal.path.EvaluationContextImpl.getValue(EvaluationContextImpl.java:133)
stderr: 	at com.jayway.jsonpath.JsonPath.read(JsonPath.java:185)
stderr: 	at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:89)
stderr: 	at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:78)
stderr: 	at io.legado.app.model.analyzeRule.AnalyzeByJSonPath.getString(AnalyzeByJSonPath.kt:44)
stderr: 	at io.legado.app.model.analyzeRule.AnalyzeRule.getString(AnalyzeRule.kt:245)
stderr: 	at io.legado.app.model.analyzeRule.AnalyzeRule.getString$default(AnalyzeRule.kt:226)
stderr: 	at io.legado.app.model.analyzeRule.AnalyzeRule$SourceRule.makeUpRule(AnalyzeRule.kt:584)
stderr: 	at io.legado.app.model.analyzeRule.AnalyzeRule.getStringList(AnalyzeRule.kt:171)
stderr: 	at io.legado.app.model.analyzeRule.AnalyzeRule.getStringList$default(AnalyzeRule.kt:157)
stderr: 	at io.legado.app.model.webBook.BookList.getSearchItem(BookList.kt:178)
stderr: 	at io.legado.app.model.webBook.BookList.analyzeBookList(BookList.kt:88)
stderr: 	at io.legado.app.model.webBook.WebBook.searchBook(WebBook.kt:74)
stderr: 	at io.legado.app.model.webBook.WebBook$searchBook$1.invokeSuspend(WebBook.kt)
stderr: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
stderr: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
stderr: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
stderr: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
stderr: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
stderr: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
stderr: 192.168.100.5 - - [2024-01-11 04:43:15] "GET / HTTP/1.1" 200 18738 0.016284
stderr: 192.168.100.5 - - [2024-01-11 04:43:15] "GET /assets/css/layout.css HTTP/1.1" 304 181 0.001793
stderr: 192.168.100.5 - - [2024-01-11 04:43:15] "GET /assets/js/myJQuery.js HTTP/1.1" 304 180 0.001746
stderr: 192.168.100.5 - - [2024-01-11 04:43:15] "GET /assets/js/title.js HTTP/1.1" 304 176 0.001768
stderr: 192.168.100.5 - - [2024-01-11 04:43:15] "GET /assets/js/hpage.js HTTP/1.1" 304 177 0.001876
stderr: 192.168.100.5 - - [2024-01-11 04:43:15] "GET /assets/js/layout.js HTTP/1.1" 304 178 0.001700
stderr: 192.168.100.5 - - [2024-01-11 04:43:15] "GET /assets/js/book.js HTTP/1.1" 304 175 0.001766
stderr: 192.168.100.5 - - [2024-01-11 04:43:15] "GET /assets/js/booklist.js HTTP/1.1" 304 180 0.001726
stderr: 192.168.100.5 - - [2024-01-11 04:43:15] "GET /assets/js/base16.js HTTP/1.1" 304 179 0.001711
stderr: 192.168.100.5 - - [2024-01-11 04:43:16] "GET /i/js/layout.js?t=1704948195874 HTTP/1.1" 404 331 0.001597
stderr: 192.168.100.5 - - [2024-01-11 04:43:16] "GET /i/js/booklist.js?t=1704948195927 HTTP/1.1" 404 331 0.001607
stderr: 192.168.100.5 - - [2024-01-11 04:43:16] "GET /index/main/log HTTP/1.1" 404 331 0.001526
stderr: 192.168.100.5 - - [2024-01-11 04:43:17] "GET /bookshelf/1 HTTP/1.1" 200 1678 0.092717
stderr: 192.168.100.5 - - [2024-01-11 04:43:22] "GET /bookshelf/1 HTTP/1.1" 200 1678 0.048089
stderr: 192.168.100.5 - - [2024-01-11 04:43:24] "GET /i/js/layout.js?t=1704948204263 HTTP/1.1" 404 331 0.001477
stderr: 192.168.100.5 - - [2024-01-11 04:43:24] "GET /i/js/booklist.js?t=1704948204318 HTTP/1.1" 404 331 0.001608
stderr: 192.168.100.5 - - [2024-01-11 04:43:26] "GET /bookshelf/-5 HTTP/1.1" 200 1680 0.046998
stderr: 192.168.100.5 - - [2024-01-11 04:43:29] "GET /i/js/layout.js?t=1704948208858 HTTP/1.1" 404 331 0.001456
stderr: 192.168.100.5 - - [2024-01-11 04:43:29] "GET /i/js/booklist.js?t=1704948208916 HTTP/1.1" 404 331 0.001432
stderr: 192.168.100.5 - - [2024-01-11 04:43:30] "GET /bookshelf/1 HTTP/1.1" 200 1678 0.046063
stderr: 192.168.100.5 - - [2024-01-11 04:43:38] "GET /index/main/log HTTP/1.1" 404 331 0.001479
stderr: 192.168.100.5 - - [2024-01-11 04:43:43] "GET /index/main/logs HTTP/1.1" 404 331 0.001427
stderr: 192.168.100.5 - - [2024-01-11 04:43:46] "GET /index/main/ HTTP/1.1" 404 331 0.001457
`

**Comment by jeavenchu** [comment]
我也是这样的报错一直无法成功，希望作者能看下

**Comment by wevcat** [comment]
> 我也是这样的报错一直无法成功，希望作者能看下

看我的库里，有两个解决方案，

**Comment by fireflyfeihuo** [comment]
> > 我也是这样的报错一直无法成功，希望作者能看下
> 
> 看我的库里，有两个解决方案，
大佬，原谅我不玩git，看了一下你的主页没找到解决方案，求救


！！！看到了，大佬！有个小需求，能不能加一个账号密码登录啊，我在reader那边搞了账号密码，现在的话是再起一个新的用着，总之谢谢大佬
